### ISSUE TITLE
IE 11 2d globe displayed incorrectly

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#57] opened 2016-04-21 13:55 UTC
When moving the globe using Internet explorer 11, it seems to display incorrectly, one image of the globe seems to move in the opposite direction of the one expected. From what I see it seems like the browser wants to keep both globes on the viewport.
![vires_services_screenshot](https://cloud.githubusercontent.com/assets/17086561/14711386/7405c4f8-07d9-11e6-944b-420a81bd500a.jpg)

**Comment by santilland** [comment] 2016-05-03 15:45
Reported bug to Cesium team, they want to tackle it for next release:
https://github.com/AnalyticalGraphicsInc/cesium/issues/3893

**Comment by lubojr** [comment] 2019-03-08 10:23
I believe this is already fixed in production, since we now have much newer cesium version

**Comment by lubojr** [comment] 2019-03-13 09:32
Tested on production and staging and the problem is still not fixed for IE11 as of now.

**Comment by pacesm** [comment] 2021-02-12 14:12
Tracing the Cesium ticket, this issue seems to be fixed in v.1.22 (June 2016). The VirES client is apparently still using older v1.20 (https://github.com/ESA-VirES/WebClient-Framework/blob/ad6db0965f5d5ec112a564ccbe03e250a5549557/bower.json#L24).

**Comment by santilland** [comment] 2021-02-12 14:51
The cesium version was fixed to this one as it uses a specific way of rendering the dots. This is then overwritten by our deploy to make sure the shader uses a solution that does not create issues where dots overlap. Starting v 1.21 they changed how points are rendered, the points no longer disappear when displayed in a specific angle, but they create artifacts at the border of the points where some pixels become transparent.
If we update the version we will need to look at how they are doing the new rendering and see if we can overwrite their shaders if we want to achieve the smooth transition between points again. (Maybe this has been solved at some point already in latest releases) would need to probably look at breaking changes depending on which version we want to use.

**Comment by pacesm** [comment] 2021-02-12 15:26
Replaced by #434

**Closed by pacesm** 2021-02-12 15:26 UTC
Labels: browser support, bug
