### ISSUE TITLE
F plot for satellite C

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#130] opened 2016-09-23 09:50 UTC
The F plot for satellite C is shown as a constant value at the top of the graph. The representation could also be considered correct but I would a value "0" on the Y axis. On the contrary, the Y axis is empty, i.e. no values are shown. Anyway, in my opinion, I think that it is better, in this case, to show the constant line at the bottom of the graph (check also the same plot on the operational platform) with the "0" value on the Y axis.

**Comment by lmar76** [comment] 2016-09-23 09:57
The same issue appears also for the Bubble Probability when it is equal to 0.

**Comment by santilland** [comment] 2016-09-26 16:34
The problem is in the domain calculation where i check the maximum and minimum values in the data, if all are equal the axis creation has some issues, in order to overcome this i check now if the domain extent is 0 and if it is the case i use a domain where i substitute the maximum value of the domain with minimum + 1 (which normally results in a domain of [0..1] in our case). I am closing this issue as i consider it solved, but if this approach is not as expected please comment here.

**Closed by santilland** 2016-09-26 16:34 UTC
