### ISSUE TITLE
Hide filters functionality not working in the Analytics View

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#243] opened 2018-04-03 14:41 UTC
Issue observed in the staging instance.

1. Select a time range containing MAG-L data -> the F plot for the selected range is displayed.
2. Select the analytic view -> the interface is updated showing only the scatterplot and the filters:

![image](https://user-images.githubusercontent.com/20207042/38256001-8fe9709c-375d-11e8-9606-f29970c1dbf4.png)

3. Click the button to hide the filters -> the filters are not shown anymore but the scatterplot is not resized:

![image](https://user-images.githubusercontent.com/20207042/38256078-bddb8b70-375d-11e8-9504-b940007710c9.png)

**Comment by santilland** [comment] 2018-04-06 15:50
There was an issue of not handling showing and closing of views cleanly, this has been adapted and the issue is no longer present. This has been pushed to staging and if after further testing everything seems ok the ticket will be closed.

**Comment by santilland** [comment] 2018-04-17 14:07
Some further testing was done, there were possibly also other related issues (such as problems with window resizing) that have been also addressed through other tickets.
I will close the ticket now as i consider it solved, if any other related problems appear please feel free to comment.

**Closed by santilland** 2018-04-17 14:07 UTC
