### ISSUE TITLE
Error while uploading CSV file

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#342] opened 2019-07-08 15:33 UTC
Error detected on staging platform.

While uploading file (previously downloaded from VirES):
[SW_OPER_MAGA_LR_1B_20170702T000000_20170702T010000_Filtered.ZIP](https://github.com/ESA-VirES/WebClient-Framework/files/3369107/SW_OPER_MAGA_LR_1B_20170702T000000_20170702T010000_Filtered.ZIP) the following error appears: 

![image](https://user-images.githubusercontent.com/20207042/60822640-25109e80-a1a6-11e9-929e-d6e210797e72.png)

**Comment by pacesm** [comment] 2019-07-08 16:31
The problem is caused by parsing of the `Flags_B` integer flag. The CSV parser parses the values as `int64` but then the CDF converter tries to save them as `CDF_INT8` variable. The mismatch between the integer types then causes the error.

This should be fairly easy to fix. I'll have look on it.

**Comment by lmar76** [comment] 2019-07-09 08:41
According to your explanation, the system converts the uploaded CSV file into CDF before visualize its content. Right?

**Comment by pacesm** [comment] 2019-07-09 09:23
Yes, the CSV is first converted to a CDF which is then used by the server.

The server needs to repeatedly read the data and feed them to the client as quickly and possible. The client then does the visualization. 
Parsing the text-based CSV file multiple times would be quite inefficient compared to the binary CDF file.

**Comment by pacesm** [comment] 2019-07-09 17:23
Fixed and deployed on staging.

**Comment by lmar76** [comment] 2019-07-11 09:48
Tested, it works!

**Comment by lmar76** [comment] 2019-07-11 10:15
Hello, I have executed a new test uploading a non-modified CSV file product previously downloaded from vires:

[SW_OPER_MAGA_LR_1B_20190101T000000_20190101T010000_Filtered.zip](https://github.com/ESA-VirES/WebClient-Framework/files/3381468/SW_OPER_MAGA_LR_1B_20190101T000000_20190101T010000_Filtered.zip)

While uploading the file, the following error appear:

![image](https://user-images.githubusercontent.com/20207042/61042778-22e05700-a3d5-11e9-8d58-c4ad3c5d3b62.png)

**Comment by pacesm** [comment] 2019-07-11 12:16
OK, I'll have look on it.

**Comment by pacesm** [comment] 2019-07-12 14:07
@lmar76
FYI, the problem was cased by mixed integer and float `ASM_Freq_Dev` values.
I reviewed the CSV parsing and made it a bit more robust.
The fix has been deployed to staging.

**Comment by lmar76** [comment] 2019-07-15 14:51
It works.

**Comment by pacesm** [comment] 2019-07-15 20:41
The issue has been assigned to the [v3.1.0 milestone](https://github.com/ESA-VirES/WebClient-Framework/milestone/4) and can be closed.

**Closed by pacesm** 2019-07-15 20:41 UTC
Labels: bug
