### ISSUE TITLE
Multiple (vertically stacked) plots with EEF

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#308] opened 2019-03-12 10:03 UTC
1. Select MAG LR product -> Plot F vs Latitude is visualized.
2. Slect EEF product in addition to MAG LR -> A second (vertically stacked) **empty** plot is visualized.
3. Deselect the MAG LR product -> The F vs Latitude plot is removed and now the EEF is visible.

![image](https://user-images.githubusercontent.com/20207042/54191527-64f49d00-44b6-11e9-833d-1789b9c9003e.png)

**Comment by pacesm** [comment] 2019-03-12 17:04
@lmar76 
FYI, I tried to reproduce this with the version 2.2.3 deployed in production (using one EEF plot) I get similar behavior and it is likely that it was present even already before.

I suspect that behavior is caused by the nature of the EEF (a point at the equator) and the way we sub-sample data fetched to the client (e.g., 1 sample per 20s). The MAGx_LR samples are too far away from the equator and not anywhere near any EEF sample. Therefore you get very few or no EEF value when MAGx_LR and EEF products are selected simultaneously and all values when only EEF is selected.

I am afraid this one cannot be quickly fixed and it would require re-working of the EEF handling in VirES.

**Comment by pacesm** [comment] 2019-03-28 08:54
@lmar76 FYI, the fix has just been deployed to staging.

Extra samples are included to so that the sparse EEF values are included in the server response.

**Comment by lmar76** [comment] 2019-04-12 12:48
Tested, thank you!

**Comment by pacesm** [comment] 2019-04-12 13:47
Already tested, deployed to staging and assigned to a milestone. I guess it is fine when I close it.

**Closed by pacesm** 2019-04-12 13:47 UTC
Labels: defect, priority high

**Comment by lmar76** [comment] 2019-04-12 14:11
Is it already in operations?
