### ISSUE TITLE
Firefox + Adblock Plus  stuck on loading screen 

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#22] opened 2016-04-04 13:29 UTC
On logging in using Firefox 45.0 I get stuck on the loading screen.

![loading](https://cloud.githubusercontent.com/assets/17086561/14248847/01448234-fa77-11e5-9d3e-4d168a19d3e8.png)

On checking the browser console using OpenSuse 13.2, I see a lot of css attribute errors from *main.css* . The first error which appears is "ReferenceError: Backbone is not defined" at the beginning of DownloadView.js:

    (function(){"use strict";var a=Backbone.Collection.extend({fetch:function(a){ret...

followed by the browser indicating *"junk after document element"*, *"undefined entity"* and *"not well-formed"* errors for several .hbs files. 

*require.js* then throws a [script error](http://requirejs.org/docs/errors.html#scripterror) *Error: Script error for "analytics"*, 

then finally from *DevToolsUtils.js* (line 63):

    TabSources.prototype._fetchSourceMap threw an exception: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    Stack: SourceMapConsumer@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/sourcemap/source-map.js:1281:20
    TabSources.prototype._fetchSourceMap/fetching<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/utils/TabSources.js:440:19
    Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
    this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
    this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:1
    EventLoop.prototype.enter@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:347:5
    ThreadActor.prototype.unsafeSynchronize@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:1075:7
    ThreadActor.prototype._addSource@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:1935:1
    ThreadActor.prototype.onNewScript@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:1882:5
    DynamicSourceCollector.prototype.onNewScript@chrome://firebug/content/debugger/script/sourceTool.js:408:1
    Line: 1281, column: 20

When trying to reproduce the same error on Windows 7 Enterprise SP1, I get no warnings but I still get the Script error for "analytics" mentioned above and it is also stuck on the loadings screen.

**Comment by santilland** [comment] 2016-04-05 15:46
Thank you for the ticket, i am looking into this.

For clarification CSS related messages are Warnings, the big majority related to the gradient definitions for representation of the color scales which look like this:

.redblue{
	width: 100%;
	height: 20px;
	margin-top: 15px;
	background: #ff0000; /* Old browsers */
	background: -moz-linear-gradient(left,  #ff0000 0%, #0000ff 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, right top, color-stop(0%,#ff0000), color-stop(100%,#0000ff)); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(left,  #ff0000 0%,#0000ff 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(left,  #ff0000 0%,#0000ff 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(left,  #ff0000 0%,#0000ff 100%); /* IE10+ */
	background: linear-gradient(to right,  #ff0000 0%,#0000ff 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ff0000', endColorstr='#0000ff',GradientType=1 ); /* IE6-9 */
}

This is to ensure compatibility of other browsers. Firefox in this case drops (ignores) the ones he does not understand (throwing warnings) and loads the one it does understand.

Warnings can be unchecked in the in the firefox debug console.
As we have agreed on supporting only latest versions of browsers i am thinking of actually removing the support for older versions which should cleanup a lot of the firefox warnings, please let me know what you think about that.

In relation to the backbone error there seems there could be an issue when loading the client for the first time where dependencies are not loaded in the expected order through the require library, i am having issues reproducing this error (even using blank instances of firefox), i am working on some solutions and will report back here.

**Comment by miktoki** [comment] 2016-04-06 08:25
You would propose to remove gradients for IE6-9 , Chrome<10, Safari<5.1, such that they would use the monochrome version `background: #ff0000;`, or do you mean to only use monochrome + W3C linear gradient ?

**Comment by santilland** [comment] 2016-04-06 09:47
So i found another solution at least for the color scales, i now just create them as image in the code and do not use css for it at all, removing all those styles. Still there is no way of cleaning all the warnings in firefox as i am getting them from all mayor libraries like bootstrap and jquery (which does not make sense to just modify). It is a normal way of handling different browsers, i hope this makes sense.
Still trying to reproduce with confidence the backbone issue.

**Comment by santilland** [comment] 2016-04-06 15:08
Ok, the backbone issue should be solved in commit 536eec03bf9e42849a6346d9d6856e7e57db1979
which is already in staging, could you see if you can reproduce the error again?

Do you still get this analytics error? I think it could be related to an unsecure reference to a image which i changed in the last push.

I am trying to reduce the warnings produced in firefox, not sure if to create separate tickets for these 3 issues, lets see if you can still reproduce the first two.

**Comment by miktoki** [comment] 2016-04-06 16:41
I no longer get the backbone error. 

I still get the following errors:
 * "junk after document element", "undefined entity" and "not well-formed" errors for several .hbs files 
 * analytics error
 * the DevToolsUtils.js (line 63) error

**Comment by santilland** [comment] 2016-04-06 17:52
Ok, after trying to work through the errors displayed by firefox, the issues is that the hbs files, they are templates so rendered on the fly more or less through a library, the templates themselves are perfectly valid but the library that loads them creates a javascript file from them which seems to confuse firefox, from what i can see this creates no issue whatsoever for firefox so i created a ticket (#27) to keep track of it but i do not consider it critical.

What i cant reproduce are the analytics error and the devtools error i have not seen them for now, testing with firefox 45

**Comment by santilland** [comment] 2016-04-07 16:04
As fas as i understood the remaining errors/warnings do not stop firefox from loading the application, is this correct? So firefox is no longer stuck on loading screen?

I will close this issue, if firefox still does not load we can reopen it.

To not loose the information 3 other tickets were created to related issues explained in this post:
#32, #27, and #33

**Comment by miktoki** [comment] 2016-04-07 16:59
This is not correct. I am still stuck on both on OpenSuse and on Windows

**Comment by santilland** [comment] 2016-04-08 07:45
I misunderstood. We need to investigate this further. Would it be possible to tell me what firefox plugins you are currently using?

**Comment by miktoki** [comment] 2016-04-08 09:05
By deactivating Adblock (default installation of Adblock Plus 2.7.2) I was able to sucessfully run it on firefox on both OS's. 

That being said, this would imply that vires is determined to be intrusive by this plugin. I tried installing the equivalent on chrome (Adblock Plus  1.11), which did not cause any problems. According to addons.mozilla there are >20M average daily users, so this might have to be addressed.

**Comment by Schpidi** [comment] 2016-04-08 09:37
The problem seems to be the EasyPrivacy list which filters out, besides a lot of others, elements with `/analytics.min.` in their URL (see https://easylist-downloads.adblockplus.org/easyprivacy.txt). Simply renaming `/eoxs_static/workspace/bower_components/analyticsviewer/lib/scripts/analytics.min.js` should hopefully help.

**Comment by constantinius** [comment] 2016-04-08 09:39
I have the same issue with Chrome and uBlock.

**Comment by Schpidi** [comment] 2016-04-08 09:45
uBlock also uses the EasyPrivacy list (see https://github.com/gorhill/uBlock)

**Comment by santilland** [comment] 2016-04-08 14:40
Renamed any file which included analytics to make sure they are not blocked by ad blockers and similar. It should be solved now, tested on multiple environments with adblocker with specific EasyPrivacy list addes. Introduced in commit d9044807fbea00e90bda4c84dcd99764b0a45bf0

**Closed by santilland** 2016-04-08 14:40 UTC
Labels: browser support, bug

**Comment by Schpidi** [comment] 2016-04-12 14:12
Btw. the adblocker also filters out the social login buttons but users of an adblocker should be aware of this.
