### ISSUE TITLE
Can't delete download link in the download manager (improvement)

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#185] opened 2017-03-17 08:48 UTC
Issue detected on v2.0 (staging).

Currently it is not possible to remove a previously saved link in the download manager. This could be a bit annoying especially if a processing fails (see screenshot) or the list of links is big. It could be useful to add a "remove" button (similar to the red one present in the "Filters" area of the download manager).

![image](https://cloud.githubusercontent.com/assets/20207042/24035656/cac85532-0af6-11e7-8851-27db26da1be0.png)

**Comment by santilland** [comment] 2017-03-17 09:15
Currently only the last two processes (and results) are saved. So when starting a new process the oldest one is removed. Only one process can be run at the same time.
The idea is to still give information and link to the previous process when starting a new process.
If we allow the user to keep more result files we need to consider the amount of available space we need to procure to be able to cater all users. 
In any case the functionality to delete processes is already available server side, so adding a delete button is not a problem, but i think we should maybe discuss how we want to handle saving of results for the user.

**Comment by santilland** [comment] 2017-03-22 20:28
The issue is the confusion of which of the two is the new one (when going to download). A possible solution is making visually clearer which one is the newest one.
Current ideas are changing visually loadin bar "ready" form previous one or adding wording to items such as new or old/previous

**Comment by santilland** [comment] 2017-04-18 14:32
![selection_093](https://cloud.githubusercontent.com/assets/4036819/25136166/82314154-2454-11e7-98d4-b7e70039d34e.png)
In order to help clarify what process is the newest we could add a sort of "table header" as in the mockup here, with some additional info which maybe is also helpful

**Comment by santilland** [comment] 2017-12-20 14:25
The table header was added for clarification, after some discussion we decided the possibility of deleting a download link was not necessary. 
I consider the current approach solves this ticket. i will close it now. If there are any other comments please feel free to do so.

**Closed by santilland** 2017-12-20 14:25 UTC
