### ISSUE TITLE
Time field not visible in the Download Manager

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#232] opened 2017-12-11 16:45 UTC
Issue observed on operational instance (v2.1) with Chrome v62.

With the Download Manager it is currently not possible to indicate a time interval because the "Time" field is not visible (see screenshot). Please note that the issue has not been detected with Internet Explorer and Firefox.

![capture](https://user-images.githubusercontent.com/20207042/33842472-ecc9c95e-de9a-11e7-8e3e-46714e5b10a2.PNG)

**Comment by santilland** [comment] 2017-12-12 09:51
As far as i can see the problem is a scrollbar is appearing in the field for some reason, i tested multiple resolutions and zoom settings and could not reproduce blocking the textfield. But in order to make sure this does not happen (could be a missmatch of textarea height and font rendering (not sure) i disabled showing scroll bar on these input fields, this should solve the problem in any case. Deployed on staging.

**Comment by lmar76** [comment] 2017-12-12 10:44
Tested on staging with Chrome (same version), IE and Firefox: the scrollbar is not visible anymore. Thanks!

**Comment by santilland** [comment] 2017-12-20 14:15
Moved to operations, closing ticket, feel free to comment for any related things.

**Closed by santilland** 2017-12-20 14:15 UTC
