### ISSUE TITLE
Incorrect list of data sources

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#441] opened 2021-03-30 10:46 UTC
Issue detected on staging.

Select: satellite A, Electric current data -> The GUI is updated with FAC data of satellite A. The list of data sources includes AOBAFAC_2F and FACATMS_2F products:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/20207042/112976494-3ad1ae80-9155-11eb-921f-5cb9938749f1.png">

In the layers list, select satellite B -> The GUI is updated with FAC data of satellite B. The list of data sources includes AOBBFAC_2F and FACBTMS_2F products *in addition* to AOBAFAC_2F and FACATMS_2F:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/20207042/112976908-b895ba00-9155-11eb-93ae-c598a5aa6234.png">

In the layers list, select satellite C -> The GUI is updated with FAC data of satellite C. The list of data sources includes AOBCFAC_2F and FACCTMS_2F products *in addition* to AOBBFAC_2F and FACBTMS_2F:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/20207042/112977136-00b4dc80-9156-11eb-9a9c-b4ad0c9f2906.png">

**Comment by pacesm** [comment] 2021-04-01 09:40
I am not able to reproduce the issue. When I select magnetic and electric current data for all A, B and C I see the correct list of products:

![image](https://user-images.githubusercontent.com/4050019/113274889-764bb480-92de-11eb-8591-1e529e8d141f.png)

Could you please re-try and see if you get the same issue again? Thanks.

**Comment by lmar76** [comment] 2021-04-06 15:56
Sorry, I did not explain correctly. In all the 3 steps I selected only one satellite:
1. Alpha (default)
2. Selected Bravo and deselected Alpha
3. Selected Charlie and deselected Bravo

At step 2 I was expecting only AOBBFAC_2F and FACBTMS_2F. At step 3 I was expecting only AOBCFAC_2F and FACCTMS_2F.

**Comment by pacesm** [comment] 2021-04-07 08:31
Thanks for the explanation. I managed to reproduce the issue. It seems it is caused by a combination of timing and slow responses of the staging server. This is issue is not exclusive to the current CR V3.5 and it is present in the current production deployments as well though much harder to get as the responses are almost instant.

If you wait enough time to load the requested data and then you deselect the product then the list is correct. 
If you however change the selection while the previous one is still loading, the response to the previous one data requests arrives later and it is added to the list.

This is not a desired behavior and we will need to find a way how to "cancel" the on-going data requests when the selection is changed.

**Comment by pacesm** [comment] 2021-04-07 14:51
The fix has been deployed on staging.

**Comment by lmar76** [comment] 2021-04-07 15:06
Testes. It works. Thank you

**Closed** 2021-04-07 15:19 UTC
Labels: defect
