### ISSUE TITLE
Found differences between residuals calculations

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#258] opened 2018-05-25 10:01 UTC
Issue detected on version v2.2 (staging).

I have downloaded the following custom products:
1. MAG-L, CHAOS-6, spacecraft A, 01/05/2016: Timestamp, Latitude, Longitude, Radius, F, F_res_CHAOS-6-Combined, B_NEC, B_NEC_res_CHAOS-6-Combined
2. MAG-L, IGRF-12 spacecraft A, 01/05/2016: Timestamp, Latitude, Longitude, Radius, F, F_res_IGRF12, B_NEC, B_NEC_res_IGRF12
3. MAG-L, SIFM spacecraft A, 01/05/2014: Timestamp, Latitude, Longitude, Radius, F, F_res_SIFM, B_NEC, B_NEC_res_SIFM

both from staging and operational platforms and compared the results, i.e. for each of the three custom products, I have compared the file downloaded from the staging platform to the file downloaded from the operational platform and I have found difference in the F/model and B_NEC/model residuals (see attached excel file). The F and B_NEC values are equal, so probably something is changed in the model calculation.

[residuals_comparisons.xlsx](https://github.com/ESA-VirES/WebClient-Framework/files/2038900/residuals_comparisons.xlsx)

**Comment by pacesm** [comment] 2018-05-25 10:28
OK, I'll have a look on it.

I suspect this rather little difference (~0.01nT) is because of the slightly different time used for the model evaluation.

In the old VirES version we used mean daily time  to interpolate the model coefficient. which were kept constant for the whole daily MAGx_LR product.

This approach it no longer possible with the new MMA_SHA models which change significantly over the day and all models now use actual time as read from the products.

This needs to be confirmed thought.

**Comment by pacesm** [comment] 2018-05-28 14:57
I checked the reported residual values and compared them with calculated model values for different inputs parameters.

**The results confirm that the differences between the operational (production) and staging residuals are caused by the different times used for the model evaluation.**

The old (operational) version evaluates models using the mean product time (noon time for the daily `MAGx_LR` products), i.e., in case of the reported Chaos-6-Combined and IGRF12 residuals at `2016-05-01T12:00:00Z` and SIFM at `2014-05-01T12:00:00Z`.

The new (staging) version evaluates the models at each product time-stamp and therefore it provides slightly more precise values.

These are the maximum deviations between the different residual values:
```
F_res_CHAOS-6-Combined (staging vs. production)       max.deviation:  0.06852459999999994 nT
F_res_CHAOS-6-Combined (staging vs. exact time)       max.deviation:  9.981659498947693e-06 nT
F_res_CHAOS-6-Combined (production vs. mean time)     max.deviation:  1.0742838393085208e-05 nT

B_NEC_res_CHAOS-6-Combined (staging vs. production)   max.deviation:  0.1289692500000008 nT
B_NEC_res_CHAOS-6-Combined (staging vs. exact time)   max.deviation:  2.185037976687454e-05 nT
B_NEC_res_CHAOS-6-Combined (production vs. mean time) max.deviation:  2.158510075389586e-05 nT

F_res_IGRF12 (staging vs. production)       max.deviation:  0.05458280999999987 nT
F_res_IGRF12 (staging vs. exact time)       max.deviation:  9.405558743846854e-06 nT
F_res_IGRF12 (production vs. mean time)     max.deviation:  1.0018848408677172e-05 nT

B_NEC_res_IGRF12 (staging vs. production)   max.deviation:  0.1374332599999999 nT
B_NEC_res_IGRF12 (staging vs. exact time)   max.deviation:  2.2289087535654062e-05 nT
B_NEC_res_IGRF12 (production vs. mean time) max.deviation:  2.2223223627548805e-05 nT

F_res_SIFM (staging vs. production)       max.deviation:  0.010130599999996548 nT
F_res_SIFM (staging vs. exact time)       max.deviation:  1.6282415337798284e-05 nT
F_res_SIFM (production vs. mean time)     max.deviation:  1.632099067450099e-05 nT

B_NEC_res_SIFM (staging vs. production)   max.deviation:  0.017371600000000598 nT
B_NEC_res_SIFM (staging vs. exact time)   max.deviation:  6.824053553344811e-05 nT
B_NEC_res_SIFM (production vs. mean time) max.deviation:  6.809418773912057e-05 nT
```

**Comment by pacesm** [comment] 2018-06-08 13:55
@lmar76 Can we close this ticket?

**Comment by lmar76** [comment] 2018-06-12 07:20
Yes!

**Closed** 2018-06-12 07:22 UTC
Labels: by design
