### ISSUE TITLE
Swarm SHC file not displayed

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#64] opened 2016-04-27 14:30 UTC
When attempting to view a new Swarm Core model D (`SW_OPER_MCO_SHA_2D_20131118T000000_20151231T234556_0102.DBL`) as a custom model the system seems to fail to parse it (400 Bad request on post), and it is not displayed. It has more comments than usual, but otherwise is a completely normal SHC file. Below are the first lines of the file.

    # Swarm L2 DCO Core field model
    # Snap-shots derived from order-isog spline models
    # There are isog-2 snap-shots per node-interval,
    # plus one at each node i.e. every isog-1 snap-shots
    # correspond to a spline node.
    # Dates are given in Years.Fraction
    # Gauss coefficient format is F15.6
    #
    # First non-comment line is describing the table:
    # N_min n_max N_times spline_order N_step(=spline_order-1) Validity_Period_Start(optional) Validity_Period_End(optional)
    # Second non-comment line is listing the dates in
    # Years.Fraction.
    #
        1    20    36     6     5     2013.9   2016.0
               2013.000000    2013.100000    2013.200000    2013.300000    2013.400000    2013.500000    2013.600000    2013.700000    2013.800000    2013.900000    2014.000000    2014.100000    2014.200000    2014.300000    2014.400000    2014.500000    2014.600000    2014.700000    2014.800000    2014.900000    2015.000000    2015.100000    2015.200000    2015.300000    2015.400000    2015.500000    2015.600000    2015.700000    2015.800000    2015.900000    2016.000000    2016.099727    2016.199454    2016.299180    2016.398907    2016.498634 
        1     0  -29465.764217  -29464.334605  -29462.928278  -29461.545361  -29460.185984  -29458.850277  -29457.538369  -29456.250388  -29454.986463  -29453.746720  -29452.531288  -29451.340296  -29450.173875  -29449.032158  -29447.915285  -29446.823401  -29445.756659  -29444.715219  -29443.699242  -29442.708877  -29441.744254  -29440.805474  -29439.892599  -29439.005656  -29438.144633  -29437.309489  -29436.500148  -29435.716510  -29434.958451  -29434.225832  -29433.518510  -29432.836341  -29432.179185  -29431.546908  -29430.939379  -29430.356465 
        1     1   -1539.055993   -1537.014157   -1534.991310   -1532.987558   -1531.003006   -1529.037760   -1527.091926   -1525.165607   -1523.258906   -1521.371928   -1519.504776   -1517.657556   -1515.830378   -1514.023349   -1512.236575   -1510.470157   -1508.724187   -1506.998745   -1505.293898   -1503.609699   -1501.946181   -1500.303357   -1498.681217   -1497.079732   -1495.498855   -1493.938523   -1492.398657   -1490.879171   -1489.379968   -1487.900943   -1486.441989   -1485.002997   -1483.583858   -1482.184465   -1480.804708   -1479.444484 
        1    -1    4847.905186    4845.469942    4843.018977    4840.552205    4838.069538    4835.570890    4833.056174    4830.525302    4827.978186    4825.414741    4822.834879    4820.238515    4817.625563    4814.995939    4812.349565    4809.686365    4807.006274    4804.309231    4801.595188    4798.864106    4796.115956    4793.350725    4790.568407    4787.769016    4784.952574    4782.119123    4779.268716    4776.401422    4773.517322    4770.616506    4767.699066    4764.765094    4761.814682    4758.847918    4755.864889    4752.865682

**Comment by pacesm** [comment] 2016-04-27 17:06
@miktoki The format differs from the SHC we have seen so far.
The issue is the extra validity range in the SHC header which confuses the SHC parser.

1    20    36     6     5     **2013.9   2016.0**

If you remove the these extra values the model works.

**Comment by miktoki** [comment] 2016-04-28 06:30
@pacesm 
This nonetheless conforms with the [L2 product specification](https://earth.esa.int/documents/10174/1514862/Swarm_L2_Product_Specification)(p 38 Table 4-5) where the first non-commented lines is the following:

| N_min | N_max | N_times | spline_order | N_step=spline_order -1 | Start validity time (optional) |Stop validity time (optional) |

**Comment by pacesm** [comment] 2016-04-28 06:38
@miktoki 
Thanks for the link. I will update the SHC parser.

**Comment by pacesm** [comment] 2016-05-04 07:08
fixed by https://github.com/ESA-VirES/MagneticModel/commit/9158e487161c45dab0b83fa7d4671fdf75fe8938

delivered with the new RPM `eoxmagmod-0.3.2` release

already deployed on `staging` and `testing` instances. Production should follow soon.

**Closed by pacesm** 2016-05-04 07:08 UTC
Labels: bug
