### ISSUE TITLE
X-axis parameters menu "behind" time bar

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#296] opened 2019-03-01 13:25 UTC
Issue detected on v2.2.3.

In analytics view mode, with filters panel disabled, the drop-down menu for the X-axis parameter selection is displayed behind the time bar

![image](https://user-images.githubusercontent.com/20207042/53640952-d8341e80-3c2d-11e9-9f7e-1340a5ca80b0.png)

**Comment by pacesm** [comment] 2019-03-11 13:57
@lmar76 fixed in staging

**Comment by lmar76** [comment] 2019-03-14 14:39
I tried again but I have the same issue:

![image](https://user-images.githubusercontent.com/20207042/54365314-e8f18500-466e-11e9-8c88-f9bea426e318.png)

I think that displaying the window *above* the selected measurement would be also fine. The important thing is that it is visible.

**Comment by pacesm** [comment] 2019-03-14 15:01
@lmar76 OK, it is a different overlay, but the problem is the same. The z-index of the overlay is below the time-slider.

**Comment by lmar76** [comment] 2019-03-14 15:07
Sorry, I have confused the issue that was affecting the X-axis with this one. I confirm that the one related to the X-axis is fixed.

**Comment by lubojr** [comment] 2019-03-15 08:31
Data point table z-index was increased to go over time slider. Deployed to staging.

**Comment by lmar76** [comment] 2019-03-19 14:09
Ok, tested.

**Closed** 2019-03-19 15:22 UTC
