### ISSUE TITLE
User data upload issues

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#332] opened 2019-05-10 09:15 UTC
1. Select satellite A , MAG-L, 01/04/2017 -> F vs Latitude plot is visualized.

2. Upload SW_OPER_EFIB_LP_1B_20170401T000000_20170401T235959_0501_MDR_EFI_LP.cdf -> nothing happens.

3. Deselect and select again the Upload checkbox in the Layers list -> the analytics view is updated showing two plots:
    - F vs Latitude showing only VirES data. The legend reports "F (upload)" but F is not included in the uploaded product.
    - Ne vs Latitude showing only VirES data (even if the Ne parameter is present in the EFI product). 
    - The color scale label in the globe view is updated to "MAGU LR 1B - F" which does not make any sense.
    - It is not possible to change the visualization settings on the globe view for the uploaded data.

**Comment by pacesm** [comment] 2019-05-10 13:36
@lmar76 

- Point 2. is a bug and it will be fixed immediately (still in the current 3.0.0 release).

- Point 3. cannot be fixed quickly. The issue is that the client is currently not aware that the variables are not present in the uploaded file and we will need to slightly modify the data fetch interface.

- > It is not possible to change the visualization settings on the globe view for the uploaded data.

     We did not manage to reproduce this issue. The controls seem to work as expected.

**Comment by pacesm** [comment] 2019-05-10 17:37
@lmar76

**Comment by pacesm** [comment] 2019-05-22 12:54
@lmar76 
FYI, point 3 was fixed by https://github.com/ESA-VirES/WebClient-Framework/pull/336
already deployed on testing

**Comment by pacesm** [comment] 2019-05-22 13:07
I have just realized that the map still shows the color-bars for the non-existent variables. I am sorry. Point 3 has not been fully resolved yet.

**Comment by santilland** [comment] 2019-05-22 15:37
The colorbars on the globe now update once the data is received only showing the ones that are actually available. This is deployed on staging now.

**Comment by lmar76** [comment] 2019-06-26 09:59
Ok, I have repeated the test and now only the colorbar (and displayed data) for MAGA LR 1B is displayed on the globe.

Changing the selected product in the layers list to EFIA LP both the EFIA LP 1B and EFIU LP 1B colorbars (and displayed data) are displayed. As far as I understood it is not possible to change the settings of the EFIU LP 1B on the globe.

**Comment by pacesm** [comment] 2019-06-26 10:10
@lmar76 
> As far as I understood it is not possible to change the settings of the EFIU LP 1B on the globe.

You should be able to change setting for the EFIU the same way like for the EFIA because the EFI is a know product type. The limitation applies to custom variables which cannot be assigned to an existing product type.

**Comment by lmar76** [comment] 2019-06-26 10:16
@pacesm sorry, I didn't see that it is possible to select "upload" in the Satellite menu of the layer settings.

**Comment by pacesm** [comment] 2019-08-30 16:20
@lmar76 Could you please check this ticket has been fully resolved? Thanks.

**Comment by lmar76** [comment] 2019-09-06 14:49
Yes, thank you!

**Comment by pacesm** [comment] 2019-09-06 14:55
Thanks.

**Closed by pacesm** 2019-09-06 14:55 UTC
