### ISSUE TITLE
Parameters window scrollbar overlapped with "x" (close) icon on macOS

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/WebClient-Framework#303] opened 2019-03-07 13:19 UTC
The scrollbar in the parameters window appears overlapped with the "x" (close) icon and, sometimes, it is not possible to close it. This issue has been detected only on macOS with Chrome, Firefox and Safari:

![schermata 2019-03-06 alle 23 15 51_upd](https://user-images.githubusercontent.com/20207042/53959354-b6321480-40e3-11e9-9c1d-2fccdbf5e23a.png)

On Windows the "x" icon appears separated from the scrollbar and the it is always possible to close the window:

![capture](https://user-images.githubusercontent.com/20207042/53959416-deba0e80-40e3-11e9-897f-9954f8466716.PNG)

**Comment by santilland** [comment] 2019-03-07 17:04
Added some margin to the right which should solve the issue.

**Comment by pacesm** [comment] 2019-03-07 17:28
deployed on staging

**Comment by lmar76** [comment] 2019-03-11 12:39
Ok, it works!

**Comment by pacesm** [comment] 2019-03-11 13:16
To be closed when v2.3.0 gets deployed in production.

**Comment by pacesm** [comment] 2019-03-19 15:26
The issue is assigned to a milestone and can be closed before the actual production deployment.

**Closed by pacesm** 2019-03-19 15:26 UTC
