### ISSUE TITLE
parameter dB_sun not in VirES MAG products

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#110] opened 2016-07-11 11:30 UTC
Magnetic products with baseline 04 added the parameter **dB_Sun**, which models the main difference between the measurements made using the VFM and ASM as a vector disturbance field caused by the sun. This parameter could not be found in the CSV and CDF output from VirES. 

*Note for future evolution*: high rate magnetic data (ie not MAGx_LR) with baseline 04 from after 18/07/2015 is incompatible with data from before this date. 

[source](https://earth.esa.int/web/guest/swarm/data-access/quality-of-swarm-l1b-l2cat2-products#22)

**Comment by pacesm** [comment] 2016-07-27 15:49
The missing `dB_Sun` was fixed by this pull request https://github.com/ESA-VirES/VirES-Server/pull/29.

The fix was already merged to the `staging` branch.

**Comment by pacesm** [comment] 2016-07-27 16:10
@miktoki can you please check the staging deployment and confirm that the issue is resolved and authorise the production deployment. Thanks.

**Comment by miktoki** [comment] 2016-07-27 18:27
@pacesm You are right. The issue has been resolved. dB_sun is accessible on the staging deployment.

Are there any other changes made which would be deployed? I found some strange behaviour on staging which I will post as another issue I think deployment to production, should wait until that is resolved.

**Comment by pacesm** [comment] 2016-07-27 20:46
Understood. Please fill another ticket and close this one. The issue described in this ticket was resolved. The deployment to production is deferred until the other issue is clarified/resolved.

**Closed** 2016-07-28 07:25 UTC
Labels: bug
