### ISSUE TITLE
IE angle dependence on area [browser support]

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#66] opened 2016-04-27 16:18 UTC
When several points are close together they become transparent. When viewing an area this becomes especially visible:

![noname](https://cloud.githubusercontent.com/assets/17086561/14859408/4bc2b030-0ca4-11e6-8466-6f690e70e149.jpg)

Possibly related to #57

**Comment by santilland** [comment] 2016-04-28 09:13
This has to do with the visualization issues i described some time ago. A good description of the issue can be found here https://github.com/AnalyticalGraphicsInc/cesium/issues/2885.
The problem is there is a kind of transparency buildup on the outer line of the dots. I used one solution at the beginning where depth was not considered correctly in the shader so there were issues of overlapping points incorrectly but no issues of disappearing points. 
Now i found what i think is the best solution here https://github.com/AnalyticalGraphicsInc/cesium/pull/3784 which is using the EXT_frag_depth WebGL extension. It works really well and solves all of the previous issues but it seems IE11 just does not support (all) WebGL extensions .... at least it looks like they closed an older ticket related to it with "won't fix" without much explanation so i would not hold my breath (https://connect.microsoft.com/IE/feedback/details/793338/ie11-feature-request-support-for-webgl-extensions).
Conclusion:
Either we go back to the old method which works equally "not so good" on all browsers or
we use the EXT_frag_depth solution which should work on all browsers but not on IE11

**Comment by miktoki** [comment] 2016-04-28 11:38
What impact do these two methods have on performance, and would it be possible to only use the old method on IE (ie, check if browser has webgl extension, then act based on that)?

**Comment by santilland** [comment] 2016-05-02 12:15
Introduced new check to see if necessary WebGL extension is available if not we now fallback to the "other solution" found where there is no transparency issue but there is an ordering issue. This should only apply to Internet Explorer and Edge browsers. Done in commit 2d7269bad2e317546e269d993ca559ef5ce72b5f
I will close this issue now as i don't see any foreseeable changes in the behavior if IE related to this issue. Maybe cesium will find a better solution for this in future releases and we can look at it then. As always any issue or feedback related to this can be done at any point as comment.

**Closed by santilland** 2016-05-02 12:15 UTC
